# Generated by Selenium IDE
import pytest
from selenium.webdriver.chrome.options import Options
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


links=[]
def playVideo(nameList):
    global links
    chrome_options = Options()  
    chrome_options.add_argument("--headless")
    driver = webdriver.Chrome(chrome_options=chrome_options)
    for name in namesList:
        print('Finding Link of {}'.format(name))
        driver.get("https://www.youtube.com/")
        driver.set_window_size(1050, 721)
        time.sleep(2)
        driver.find_element(By.NAME, "search_query").click()
        driver.find_element(By.NAME, "search_query").send_keys(name)
        driver.find_element(By.CSS_SELECTOR, "#search-icon-legacy > .style-scope:nth-child(1)").click()
        time.sleep(4)
        j=driver.find_element_by_partial_link_text(name[:len(name)//2])
        link=(j.get_attribute('href')) 
        # driver.get(link)
        links.append(link)
        # time.sleep(5)
    driver.close()

with open('youtube_input.txt', 'r') as f:
    l = f.readlines()

namesList=[]
for i in l:
    namesList.append(i[:len(i)-1])

playVideo(namesList)
chrome_options = Options()  
chrome_options.add_argument("--incognito")
driver = webdriver.Chrome(chrome_options=chrome_options)
for i in links:
    driver.get(i)
    time.sleep(10)